#!/usr/bin/env python3
"""Generate ISR declaration header and function-pointer table (SlopOS, 0BSD)."""
import sys

def gen(out_c, out_h):
    c = []
    c.append("/* Generated by tools/genisr.py. SlopOS 0BSD. */")
    c.append("#include \"idt.h\"")
    c.append("")
    for n in range(256):
        c.append("extern void isr%d(void);" % n)
    c.append("")
    c.append("void (*const isr_table[256])(void) = {")
    for n in range(256):
        c.append("    isr%d," % n)
    c.append("};")
    c.append("")
    with open(out_c, "w") as f:
        f.write("\n".join(c))
    h = []
    h.append("#ifndef SLOPOS_ISR_TABLE_H")
    h.append("#define SLOPOS_ISR_TABLE_H")
    h.append("")
    h.append("extern void (*const isr_table[256])(void);")
    h.append("")
    h.append("#endif")
    with open(out_h, "w") as f:
        f.write("\n".join(h))
    print("generated isr table")

if __name__ == "__main__":
    gen(sys.argv[1], sys.argv[2])
